### ISSUE TITLE
Nucleotide context

### ISSUE THREAD

**Issue by alhafidzhamdan** [mskilab/fishHook#11]
Hi there @mskilab @imielinski 
I have a maf file containing ssvs for 100 samples.
How do i get the nucleotide context for these samples?
Do i need to generate nucleotide context for each one and average across the samples?
Or is there a generic nucleotide context that can be used?
I am using hg38.
Thanks for your help!
A

**Comment by xtYao** [comment]
https://bioconductor.org/packages/release/bioc/vignettes/Biostrings/inst/doc/BiostringsQuickOverview.pdf
