### ISSUE TITLE
exome coverage file for hg38

### ISSUE THREAD

**Issue by Sumithrasank** [mskilab/fishHook#16]
Hi,
In the exome part of the fishHook suite, is there is a file for hg38 analogous to 
exomecov = import('http://mskilab.com/fishHook/hg19/exome_coverage.bw')?
Or, is there a way to liftover the bigwig file from hg19 to hg38?
Thanks

**Comment by mskilab** [comment]
There is not - but you can use rtracklayer::liftOver to lift over.

Just FYI for the tool to "work" ie give you accurate drivers .. the
coverage of the exomes that you are analyzing should approximately match
your assay.  So doing liftover or using exome coverage from a different
flavor of exome may distort results ..

Marcin

**Comment by Sumithrasank** [comment]
Thank you
