### ISSUE TITLE
offset(eligible) should be offset(log(eligible))? 

### ISSUE THREAD

**Issue by walaj** [mskilab/fishHook#2]
@karinkumar and I were debugging our model and noticed a math bug. Because the covariate terms are exponentiated in the likelihood function for a negative binomial regression, and the offset is a scaling term (e.g. half as much eligible territory should predict half as many events), the offset term should be log'ed first.

See pages 1 and 2 of https://ncss-wpengine.netdna-ssl.com/wp-content/themes/ncss/pdf/Procedures/NCSS/Negative_Binomial_Regression.pdf noting that ``t_i`` is ``ln(t_i)`` in the likelihood.

It seems everywhere I look for ``glm.nb``, they all use offset(log(x)). e.g. https://stats.stackexchange.com/questions/180260/r-glm-nb-and-when-to-consider-using-an-offset-or-including-a-covariate

This makes a difference. See the covariates plot below. Darkest red is evenly spaced bins with ``offset(log(eligible))``. Medium-red is ``offset(eligible)``. The green bars are binned so that each bin covers almost exactly the same amount of eligible territory, so the parameterization of the offset should not matter.

![image](https://user-images.githubusercontent.com/6922120/47380729-180d5700-d6cc-11e8-9ed9-4fc1a418bbce.png)

**Comment by mskilab** [comment]
Hmm this is already taken into account - score.hypotheses runs glm.nb on
the tdt data frame after log transforming the eligible column ..

tdt$eligible = ifelse(tdt$eligible ==0, NA, log(tdt$eligible))

https://github.com/mskilab/fishHook/blob/master/R/fishhook.R#L833

**Comment by walaj** [comment]
Ahhh got it! False alarm. Good exercise though for us in understanding what's going on...

Side question: Is there a place or option for scaling covariates within Fishhook? We'd like to be able to compare difference coefficients from the model with each other, accounting for the different scales of the covariates. I guess this is usually done with ``scale(...)``?

**Comment by mskilab** [comment]
Ha ... good exercise for you, tiny heart attack for me! :)

No option inside fishHook but you can either transform (numeric) track
values before Covariate instantiation or should be fine to just rescale the
effect sizes to the desired units after you run the model.

The raw effect sizes in the glm.nb represent the change in expected *log*
mutation count for each *unit* change in the covariate value.   These
coefficients represent "log relative risk".

(pro tip: If you use $coefficients function to a scored fishHook model it
will return effect sizes as relative risks.)

Intuition for interpreting relative risks: for example, for an "interval"
covariate (whose value is always between 0 and 1) the relative risk R
corresponds to the ratio of mutation counts when the covariate is = 1 vs
when it is = 0 (obviously extrapolated by the model if the covariate never
achieves either of these values in the data).

To rescale the relative risk R to say a 0.01 change in the value of the
interval covariate you could do R2 = exp(log(R)/100) or R2 = R^(1/100)

If you're interested in whether to log transform (numeric) covariates prior
to the model - not sure if there are great rules.   But, if you have strong
reason to believe that a k-fold increase in a numeric covariate value will
create a ~k fold increase in the mutation density, then that is a good
reason to log transform before creating the covariate.

Hope that helps
Marcin

**Comment by walaj** [comment]
Marcin -- this is *incredibly* helpful. I'll take further discussion to outside of this Github issue report, but in short, we're re-thinking how we present the effect sizes to make it more clear exactly what each one means (i.e. by adding units to them as you say above).
