### ISSUE TITLE
Could not find function Cov

### ISSUE THREAD

**Issue by karinkumar** [mskilab/fishHook#6]
Hello Marcin,

I've been using Fishhook to run the 1D model for Rameen. I needed to run it again and had to reinstall the package to use on a different version of R. Now when I try to create a covariate object (for instance, if I run this line in your tutorial  hetchrom = Cov(hetchromdata, name = 'Heterochromatin')) I get the error: could not find function "Cov". 

A version of fishhook I installed months ago still works, so possibly something has changed since then?

**Comment by mskilab** [comment]
hmm maybe try downloading and reinstalling from git again? I did a recent
merge with Jeremiah's commit which was failing on Travis (though not with
that error), but my most recent push (ie this afternoon) passes.

**Comment by karinkumar** [comment]
Thanks that worked!
